CREATE TABLE vk_video(
 owner_id BIGINT NOT NULL,
  vid BIGINT NOT NULL,
 id BIGINT,
  hash CHARACTER VARYING (255),

  CONSTRAINT vk_video_pkey PRIMARY KEY (id),
  CONSTRAINT fk_nyqdks02u4i980u5k5xa8br67 FOREIGN KEY (id)
      REFERENCES video (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);